function boundariesPxInd = convertBoundariesToPxInd(boundaries, imgSize)

% check if each boundary is close to an edge or not
boundariesCat = cat(1, boundaries{:});

% look at all surrounding pixels: if at least one of them is an edge, we're good!
boundariesPxInd = unique(cat(1, ...
    sub2ind(imgSize([1 2]), min(max(boundariesCat(:,2)-0.5, 1), imgSize(1)), min(max(boundariesCat(:,1)-0.5, 1), imgSize(2))), ...
    sub2ind(imgSize([1 2]), min(max(boundariesCat(:,2)-0.5, 1), imgSize(1)), min(max(boundariesCat(:,1)+0.5, 1), imgSize(2))), ...
    sub2ind(imgSize([1 2]), min(max(boundariesCat(:,2)+0.5, 1), imgSize(1)), min(max(boundariesCat(:,1)-0.5, 1), imgSize(2))), ...
    sub2ind(imgSize([1 2]), min(max(boundariesCat(:,2)+0.5, 1), imgSize(1)), min(max(boundariesCat(:,1)+0.5, 1), imgSize(2)))));

